services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
      - /app/node_modules
    command: npm run dev
