version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/app:/app
    command: npm run dev
